name: Oxlint

on:
 pull_request:
  branches: [master, main]

jobs:
 lint:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4
  - uses: oven-sh/setup-bun@v2
  - run: bun i
  - name: Run oxlint
    run: bun run lint
 test:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4
  - uses: oven-sh/setup-bun@v2
  - run: bun i
  - name: Run vitest
    run: bunx vitest run
