name: Release & Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish to npm & GitHub
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: oven-sh/setup-bun@v2
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps
        run: bun i

      - name: Build
        run: bun run build

      - name: Publish to npm
        run: bunx npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: false
